name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-slim

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Setup pnpm
        uses: pnpm/setup@v3
        with:
          install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm typecheck

      - name: Run tests
        run: pnpm run test
        env:
          CI: true

      - name: Build project
        run: pnpm run build
        env:
          CI: true
